blog/urls.py
from blog.views import ArticleListView
from blog.views import ArticleDetailView
from django.conf.urls import include
from django.conf.urls import url

urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='blog-list'),
#    url(r'^articles/(?P<article_name>(?!.*[\W]))/$', ArticleDetailView.as_view(), name='article'),
    url(r'^articles/(?P<article_name>[-\w]+)/$', ArticleDetailView.as_view(), name='article'),
#    url(r'^articles/(?P<article_id>\d+)$', ArticleDetailView.as_view(), name='article'),

#    url(r'^categorys/(?P<tag>(?!.*[\W]))/$', CategoryView.as_view, name='categorys'),
#    url(r'^tags/(?P<tag>(?!.*[\W]))/$', TagView.as_view, name='tags'),
]

django_web_server/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve
from django_web_server.views import TemplateErrorView404
from oauth2client.contrib.django_util import site 

import os 

# project site root
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^oauth2/', include(site.urls)),
]

# for ssl file from sslforfree.com
urlpatterns += [
    url(r'^.well-known/acme-challenge/(?P<path>.*)$', serve, {
        'document_root': os.path.join(settings.STATIC_ROOT, 'ssl/'), 
    }),
]

# homepage app
urlpatterns += [
    # Notice the expression does not end in $, 
    # that happens at the myapp/url.py level
    url(r'^', include('homepage.urls', namespace='homepage', app_name='homepage')),
]

# login app
urlpatterns += [
    url(r'^login/', include('login.urls', namespace='login', app_name='login')),
]

# portfolio app
urlpatterns += [
    url(r'^portfolio/', include('portfolio.urls', namespace='portfolio', app_name='portfolio')),
]

# blog app
urlpatterns += [
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# custom error view
handler404 = TemplateErrorView404.as_view()

blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Article(models.Model):
    # enum of access Permission 
    ACCESS_PERMISSION = {
        0: u'manager',
        1: u'member',
        2: u'guest',
    }

    # title size
    title = models.CharField('Title', max_length=100, unique=True)

    # unique article id
    unique_name = models.CharField('Unique ID', max_length=100, unique=True, primary_key=True)

    # body of content
    body = RichTextUploadingField('Content', null=True, blank=True, config_name='default')

    # excerpt of content
    excerpt = models.CharField('Abstract', max_length=200, blank=True)

    # Access permission
    access = models.IntegerField('Access Permission', default=2, choices=ACCESS_PERMISSION.items())

    # classification by category (one to many)
    category = models.ForeignKey('Category', null=True, on_delete=models.SET_NULL, blank=True)

    # classification by tag (many to many)
    tag = models.ManyToManyField('Tag', blank=True)

    # Counter of likes 
    likes = models.PositiveIntegerField('Likes Counter', default=0)

    # Counter of views
    views = models.PositiveIntegerField('Views Counter', default=0)
    
    # record to article crate and modify time
    created_time = models.DateTimeField(default=timezone.now)
    published_time = models.DateTimeField(blank=True, null=True)
    modified_time = models.DateTimeField(blank=True, null=True)

    def can_access(self, user):
        if self.access == 2:
            return True
        elif self.access == 1 and user.id: 
            return True 
        elif self.access == 0 and user.is_staff:
            return True 
            
        return False 
    
    def publish(self):
        self.published_time = timezone.now()
        self.save()

    def modify(self):
        self.modified_time = timezone.now()
        self.save()
    
    def __str__(self):
        return self.title

    class Meta: 
        ordering = ['-created_time']

blog/views.py
from blog.models import Article, Category, Tag 
from django.conf import settings
from django.views.generic import DetailView, ListView 
from oauth2client.contrib.django_util import decorators
from pandas import DataFrame
from utility.google_analytics_api import GoogleAanalyticsService

# Global constant
ITEMS_PER_PAGE = 1

# Create your views here.
class ArticleListView(ListView):
    context_object_name = "context_article_list" 
    model = Article
    template_name = "blog/blog-list.html"
    paginate_by = ITEMS_PER_PAGE 

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        kwargs['recent_article_list'] = Article.objects.all().order_by('-created_time')[0:5]
        kwargs['browse_type'] = self.request.GET.get('browse')
        kwargs['ckeditor_folder'] = settings.CKEDITOR_UPLOAD_PATH

        # Get GA data 
        ga_data = GoogleAanalyticsService().get_ga_data(dimensions=None)
        visitors = str(ga_data['totalsForAllResults']['ga:entrances']).zfill(6)
        kwargs['visitors'] = visitors
        settings.BLOG_SETTINGS = visitors
        return super(ArticleListView, self).get_context_data(**kwargs)   

    def get_queryset(self):
        queryset = Article.objects.all()
        if self.request.GET.get('browse'):
            res = self.request.GET.get('browse')
            if res == 'Tag':
                queryset = Tag.objects.all()
            elif res == 'Category':
                queryset = Category.objects.all()
            else:
                queryset = Article.objects.all()
        return queryset 

class ArticleDetailView(DetailView):
    context_object_name = 'context_article'
    model = Article
    template_name = "blog/blog-article.html"
    pk_url_kwarg = 'article_name'
    
    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        kwargs['recent_article_list'] = Article.objects.all().order_by('-created_time')[0:5]
        kwargs['ckeditor_folder'] = settings.CKEDITOR_UPLOAD_PATH

        # Get GA data 
        ga_data = GoogleAanalyticsService().get_ga_data(filters=self.kwargs['article_name'])
        views = ga_data['rows'][0][3]
        kwargs['visitors'] = settings.BLOG_SETTINGS
        kwargs['views'] = ga_data['rows'][0][3]

        # model operation
        article_model = Article.objects.get(unique_name=self.kwargs['article_name'])
        article_model.views = views
        article_model.save()

        context = super(ArticleDetailView, self).get_context_data(**kwargs)   
        return context 

    def get_object(self, queryset=None):

        return super(ArticleDetailView, self).get_object()

    def get(self, request, *args, **kwargs):
        return super(ArticleDetailView, self).get(request, *args, **kwargs)

blog/templates/blog/blog-article.html
{# blog/blog-article.html #}
{% extends 'blog/blog-base.html' %}
{% load static %}
{% load disqus_tags %}

<!-- === BEGIN HEADER === -->
{% block import_css_file %}
<!-- CKEditor Plugins -->
<link rel="stylesheet" type="text/css" href="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism.css' %}">
{% endblock %}
<!-- === END HEADER === -->

<!-- === BEGIN CONTENT === -->
{% block blog_content %}
                <!-- Blog Post -->
                <div class="blog-post">
                    <div class="blog-item-header">
                        <h2>
                            <a href="#">
                                {{ context_article.title }}
                            </a>
                        </h2>
                        <!-- Date -->
                        <div class="blog-post-date">
                            <a href="#">
                                {{ context_article.created_time|date:'jS M, Y' }}
                            </a>
                        </div>
                        <!-- End Date -->
                    </div>
                    <div class="blog-post-details">
                        <!-- Tags -->
                        <div class="blog-post-details-item blog-post-details-item-left blog-post-details-tags">
                            <i class="fa fa-tag color-gray-light"></i>
                            {% for tag in context_article.tag.all %}
                                <a href="#">{{ tag }}</a>
                            {% endfor %}
                        </div>
                        <!-- End Tags -->
                        <!-- # of Comments -->
                        <div class="blog-post-details-item blog-post-details-item-left blog-post-details-item-last">
                            <a href="">
                                <i class="fa fa-eye color-gray-light"></i>
                                {{views}} Views
                            </a>
                        </div>
                        <!-- End # of Comments -->
                    </div>
                    <div class="blog-item">
                        <div class="clearfix"></div>
                        <div class="blog-post-body row margin-top-15">
                            <div class="col-md-12">
                            {{ context_article.body|safe }}
                            </div>
                        </div>
                        <div class="blog-item-footer">
                            <h1>Comments</h1>
                            <div class="blog-comment-heading"></div>
                            <!-- Comments -->
                            {% disqus_show_comments %}  
                            <!-- End Comments -->
                        </div>
                    </div>
                </div>
                <!-- End Blog Post -->
{% endblock %}
<!-- === END CONTENT === -->


<!-- === BEGIN FOOTER === -->
<!-- JS -->
{% block import_js_file %}
<!-- CKEditor Config/Plugins -->
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<!-- Disqus Config/Plugins -->
<script type="text/javascript" src="http://disqus.com/forums/arthurkozielsblog/embed.js"></script>
{% endblock %}
<!-- End JS -->
<!-- === END FOOTER === -->

blog/templates/blog/blog-base.html
{# blog/blog-base.html #}
{% extends 'base.html' %}
{% load static %}
{% get_media_prefix %}

<!-- === BEGIN HEADER === -->
<!-- Top Menu -->
{% block menu_blog %} active {% endblock %}
<!-- End Top Menu -->
<!-- === END HEADER === -->


<!-- === BEGIN CONTENT === -->
{% block content %}
<div id="content">
    <div class="container background-white">
        <div class="row margin-vert-30">
            <!-- Main Column -->
            <div class="col-md-9">
                {% block blog_content %}{% endblock %}
            </div>
            <!-- End Main Column -->
            <!-- Side Column -->
            <div class="col-md-3">
                <!-- Blog Tags -->
                <div class="blog-tags">
                    <h3>Tags</h3>
                    <ul class="blog-tags">
                        {% for tag in tag_list %}
                        <li>
                            <a href="#" class="blog-tag">{{ tag.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- End Blog Tags -->
                <!-- Recent Posts -->
                <div class="recent-posts">
                    <h3>Recent Posts</h3>
                    <ul class="posts-list margin-top-10">
                        {% for article in recent_article_list %}
                        <li>
                            <div class="recent-post">
                                <a href="{% url 'blog:article' article.pk %}">
                                    <img class="pull-left" src="{{ MEDIA_URL }}{{ ckeditor_folder }}{{ article.created_time|date:'Y/m/d/' }}Title.jpg" width="54">
                                </a>
                                <a href="{% url 'blog:article' article.pk %}" class="posts-list-title">{{ article.title }}
                                </a>
                                <br>
                                <span class="recent-post-date"> {{ article.created_time|date:'M d, Y'}}</span>
                            </div>
                            <div class="clearfix"></div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- End Recent Posts -->

                <!-- Visitor Counter -->
                <div class="recent-posts">
                    <h3>Visitor</h3>
                    <div data-theme="car" class="odometer odometer-theme-car">
                        <div class="odometer-inside">
                            {% for number in visitors %}<span  class="odometer-digit"><span class="odometer-digit-spacer">8</span><span class="odometer-digit-inner"><span class="odometer-ribbon"><span class="odometer-ribbon-inner"><span class="odometer-value">{{ number }}</span></span></span></span></span>{% if forloop.counter|divisibleby:3 and not forloop.last%}<span class="odometer-formatting-mark">,</span>{% endif %}{% endfor %}
                        </div>
                    </div>
                </div>
                <!-- End Visitor Counter -->

            </div>
            <!-- End Side Column -->
        </div>
    </div>
</div>
{% endblock %}
<!-- === END CONTENT === -->

blog/templates/blog/blog-list.html
{# blog/blog-list.html #}
{% extends 'blog/blog-base.html' %}
{% load static %}

<!-- === BEGIN CONTENT === -->
{% block blog_content %}
            <!-- Blog Main List -->
                <!-- Blog Item -->
                {% for article in context_article_list %}
                <div class="blog-post padding-bottom-30">
                    <!-- Blog Item Header -->
                    <div class="blog-item-header">
                        <!-- Title -->
                        <h2>
                              <a href="{% url 'blog:article' article.pk %}"> {{ article.title }} </a>
                        </h2>
                        <div class="clearfix"></div>
                        <!-- End Title -->
                        <!-- Date -->
                        <div class="blog-post-date">
                            <a href="#">
                                {{ article.created_time|date:'jS M, Y' }}
                            </a>
                        </div>
                        <!-- End Date -->
                    </div>
                    <!-- End Blog Item Header -->
                    <!-- Blog Item Details -->
                    <div class="blog-post-details">
                        <!-- Tags -->
                        <div class="blog-post-details-item blog-post-details-item-left blog-post-details-tags">
                            <i class="fa fa-tag color-gray-light"></i>
                            {% for tag in article.tag.all %}
                                <a href="#">{{ tag }}</a>
                            {% endfor %}
                        </div>
                        <!-- End Tags -->
                        <!-- # of Comments -->
                        <div class="blog-post-details-item blog-post-details-item-left blog-post-details-item-last">
                            <a href="">
                                <i class="fa fa-eye color-gray-light"></i>
                                {{ article.views}} Views
                            </a>
                        </div>
                        <!-- End # of Comments -->
                    </div>
                    <!-- End Blog Item Details -->
                    <!-- Blog Item Body -->
                    <div class="blog">
                        <div class="clearfix"></div>
                        <div class="blog-post-body row margin-top-15">
                            <div class="col-md-5">
                                <img class="margin-bottom-20" src="{{ MEDIA_URL }}{{ ckeditor_folder }}{{ article.created_time|date:'Y/m/d/' }}Title.jpg">
                            </div>
                            <div class="col-md-7">
                                <p>{{article.excerpt |safe}}</p>
                                <!-- Read More -->
                                <a href="{% url 'blog:article' article.pk %}" class="btn btn-primary">
                                    Read More
                                    <i class="icon-chevron-right readmore-icon"></i>
                                </a>
                                <!-- End Read More -->
                            </div>
                        </div>
                    </div>
                    <!-- End Blog Item Body -->
                </div>
                {% endfor %}
                <!-- End Blog Item -->

                <!-- Pagination -->
                {% if page_obj.has_previous or page_obj.has_next %}
                <ul class="pagination">
                    <!-- Pagination for previous check -->
                    {% if page_obj.has_previous %}
                    <li>
                        <a href="{{ request.path }}?browse={{ browse_type }}&page=1">&laquo;</a>
                    </li>
                    <li>
                        <a href="{{ request.path }}?browse={{ browse_type }}&page={{ page_obj.previous_page_number }}">Prev</a>
                    </li>
                    {% else %}
                    <li class="disabled"><a>&laquo;</a></li>
                    <li class="disabled"><a>Prev</a></li>
                    {% endif %}
                    <!-- End Pagination for previous check -->
                    <!-- Pagination for list generation -->
                    {% for page in page_obj.paginator.page_range %}
                    <li {% if page_obj.number == page %} class="active" {% endif %}>
                        <a href="{{ request.path }}?browse={{ browse_type }}&page={{ page }}"> {{ page }}</a>
                    </li>
                    {% endfor %}
                    <!-- End Pagination for list generation -->
                    <!-- Pagination for next check -->
                    {% if page_obj.has_next %}
                    <li>
                        <a href="{{ request.path }}?browse={{ browse_type }}&page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                    <li>
                        <a href="{{ request.path }}?browse={{ browse_type }}&page={{ paginator.num_pages }}">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="disabled"><a>Next</a></li>
                    <li class="disabled"><a>&raquo;</a></li>
                    {% endif %}
                    <!-- End Pagination for next check -->
                </ul>
                {% endif %}
                <!-- End Pagination -->
            <!-- End Blog Main List -->
{% endblock %}
<!-- === END CONTENT === -->