blog/urls.py
from blog.views import ArticleListView
from blog.views import ArticleDetailView
from django.conf.urls import include
from django.conf.urls import url

urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='blog-list'),
#    url(r'^articles/(?P<article_name>(?!.*[\W]))/$', ArticleDetailView.as_view(), name='article'),
    url(r'^articles/(?P<article_name>[-\w]+)/$', ArticleDetailView.as_view(), name='article'),
#    url(r'^articles/(?P<article_id>\d+)$', ArticleDetailView.as_view(), name='article'),

#    url(r'^categorys/(?P<tag>(?!.*[\W]))/$', CategoryView.as_view, name='categorys'),
#    url(r'^tags/(?P<tag>(?!.*[\W]))/$', TagView.as_view, name='tags'),
]

django_web_server/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve
from django_web_server.views import TemplateErrorView404
from oauth2client.contrib.django_util import site 

import os 

# project site root
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^oauth2/', include(site.urls)),
]

# for ssl file from sslforfree.com
urlpatterns += [
    url(r'^.well-known/acme-challenge/(?P<path>.*)$', serve, {
        'document_root': os.path.join(settings.STATIC_ROOT, 'ssl/'), 
    }),
]

# homepage app
urlpatterns += [
    # Notice the expression does not end in $, 
    # that happens at the myapp/url.py level
    url(r'^', include('homepage.urls', namespace='homepage', app_name='homepage')),
]

# login app
urlpatterns += [
    url(r'^login/', include('login.urls', namespace='login', app_name='login')),
]

# portfolio app
urlpatterns += [
    url(r'^portfolio/', include('portfolio.urls', namespace='portfolio', app_name='portfolio')),
]

# blog app
urlpatterns += [
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# custom error view
handler404 = TemplateErrorView404.as_view()

homepage/urls.py
from django.conf.urls import include
from django.conf.urls import url
from homepage.views import HomePageView, AboutMeView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name = 'homepage'),
    url(r'^about-me$', AboutMeView.as_view(), name = 'about-me'),
]

portfolio/urls.py
from django.conf.urls import include
from django.conf.urls import url
from portfolio.views import PortfolioListView, PortfolioDetailView

urlpatterns = [
    url(r'^$', PortfolioListView.as_view(), name = 'portfolio-list'),
    #url(r'^portfolio/(?P<portfolio-item-name>[-\w]+)/$', PortfolioDetailView.as_view(), name='portfolio-item'),
]

templates/base.html
<!DOCTYPE html>
{# base.html #}
{% load static %}
{% load crispy_forms_tags %}
{% load analytical %}

<!-- === BEGIN HEADER === -->
<!--[if IE 8]>
<html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    {% analytical_head_top %}
    <!-- Title -->
    <title>[Kai-Hung Huang] - Welcome come to my professional blog!</title>
    <!-- Meta -->
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'common/img/favicon.jpg'%}">
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/bootstrap.css' %}">
    <!-- Template CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/font-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/nexus.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/responsive.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/counter.css' %}">
    <!-- Google Fonts-->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300">
    {% block import_css_file %}{% endblock%}
    {% analytical_head_bottom %}
</head>
<body>
{% analytical_body_top %}
{% block phone_email %}
<div id="body-bg">
    <!-- Phone/Email -->
    <div id="pre-header" class="background-gray-lighter">
        <div class="container no-padding">
            <div class="row hidden-xs">
                <div class="col-sm-6 padding-vert-5">
                    <strong>Phone:</strong>&nbsp;+886-925-133-902
                </div>
                <div class="col-sm-6 padding-vert-5 text-right">
                    <strong>Email:</strong>&nbsp;randy.hunang@gmail.com
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<!-- End Phone/Email -->
<!-- Header -->
<div id="header">
    <div class="container">
        <div class="row">
            <!-- Logo -->
            <div class="logo">
                <a href="{% url 'homepage:homepage' %}" title="">
                    <img src="{% static 'common/img/name_logo.png' %}" alt="Logo"/>
                </a>
            </div>
            <!-- End Logo -->
        </div>
    </div>
</div>
<!-- End Header -->
<!-- Top Menu -->
<div id="hornav" class="bottom-border-shadow">
    <div class="container no-padding border-bottom">
        <div class="row">
            <div class="col-md-8 no-padding">
                <div class="visible-lg">
                    <ul id="hornavmenu" class="nav navbar-nav">
                        <li>
                            <a href="{% url 'homepage:homepage' %}"
                               class="fa-home {% block menu_home %}{% endblock %}">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'portfolio:portfolio-list' %}"
                                class="fa-th {% block menu_portfolio %}{% endblock %}">Portfolio</a>
                        </li>
                        <li>
                            <a href="{% url 'homepage:about-me' %}"
                                class="fa-copy {% block menu_pages %}{% endblock %}">About Me</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:blog-list' %}?browse=Article"
                               class="fa-font {% block menu_blog %}{% endblock %}">Blog</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 no-padding">
                <ul class="social-icons pull-right">
                    <li class="social-rss">
                        <a href="#" target="_blank" title="RSS"></a>
                    </li>
                    <li class="social-linkedin">
                        <a href="https://www.linkedin.com/in/kai-hung-huang-344117106" target="_blank"
                           title="LinkedIn"></a>
                    </li>
                    <li class="social-facebook">
                        <a href="https://www.facebook.com/randy.huang.37" target="_blank" title="Facebook"></a>
                    </li>
                    <li class="social-github">
                        <a href="https://github.com/Randy-Huang" target="_blank" title="GitHub"></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End Top Menu -->
<!-- === END HEADER === -->


<!-- === BEGIN CONTENT === -->
{% block content %}{% endblock %}
<!-- End Portfolio -->


<!-- === END CONTENT === -->
<!-- === BEGIN FOOTER === -->
<div id="base">
    <div class="container bottom-border">
        <div class="row">
            <!-- Disclaimer -->
            <div class="margin-top-30 margin-bottom-30 col-md-8">
                <h3 class="class margin-bottom-10">The Blog Disclaimer</h3>
                <ul>
                    <li>Any views or opinions represented in this blog belong solely to the blog owner and do not
                        represent those of people, institutions or organizations that the owner may or may not be
                        associated with in professional or personal capacity, unless explicitly stated.
                    </li>
                    <li>Any views or opinions are not intended to malign any religion, ethnic group, club, organization,
                        company, or individual.
                    </li>
                    <li>If there is an image appearing on this blog that belongs to you and do not wish for it appear on
                        this blog, please E-mail with a link to said image and it will be removed immediately.
                    </li>
                    <li>All content provided on this blog is for informational purposes only. The owner of this blog
                        makes no representations as to the accuracy or completeness of any information on this site or
                        found by following any link on this site.
                    </li>
                    <li>Please noted the information in this weblog is provided “AS IS” with no warranties, and confers
                        no rights.
                    </li>
                </ul>
            </div>
            <!-- End Disclaimer -->
            <!-- Contact Details -->
            <div class="margin-top-30 margin-bottom-30 col-md-4">
                <h3 class="margin-bottom-10">Contact Details</h3>
                <p>
                    <span class="fa-phone">Telephone: </span>+886-925-133-902
                    <br>
                    <span class="fa-envelope">Email: </span>
                    <a href="randy.hunang@gmail.com">randy.hunang@gmail.com</a>
                    <br>
                    <span class="fa-link">Website: </span>
                    <a href="https://www.kaihunghuang.info">www.kaihunghuang.info</a>
                    <br>
                    <span class="fa-github">GitHub: </span>
                    <a href="https://github.com/Randy-Huang">github.com/Randy-Huang</a>
                    <br>
                    <span class="fa-linkedin">Linkedin: </span>
                    <a href="https://www.linkedin.com/in/kai-hung-huang-344117106/">linkedin.com/Kai-Hung Huang</a>
                    <br>
                    <span class="fa-map-marker">Address: </span> 3F., No.3-2, Ln. 180, Sec. 1, Zhongshan N. Rd., Tamsui
                    Dist., New Taipei City 251, Taiwan (R.O.C.)
                </p>
            </div>
            <!-- End Contact Details -->
        </div>
    </div>
</div>
<!-- Footer -->
<div id="footer" class="background-grey">
    <!-- Copyright -->
    <div id="copyright">
        <p class="align-middle text-center">Copyright (c) 2017 kaihunghuang.info All rights reserved</p>
    </div>
    <!-- End Copyright -->
</div>
<!-- End Footer -->
<!-- JS -->
<script type="text/javascript" src="{% static 'common/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'common/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'common/js/scripts.js' %}"></script>
<!-- Block UI - for loading to wait event -->
<script type="text/javascript" src="{% static 'common/js/jquery.blockUI.js' %}"></script>
<!-- Isotope - Portfolio Sorting -->
<script type="text/javascript" src="{% static 'common/js/jquery.isotope.js' %}"></script>
<!-- Mobile Menu - Slicknav -->
<script type="text/javascript" src="{% static 'common/js/jquery.slicknav.js' %}"></script>
<!-- Animate on Scroll-->
<script type="text/javascript" src="{% static 'common/js/jquery.visible.js' %}" charset="utf-8"></script>
<!-- Sticky Div -->
<script type="text/javascript" src="{% static 'common/js/jquery.sticky.js' %}" charset="utf-8"></script>
<!-- Slimbox2-->
<script type="text/javascript" src="{% static 'common/js/slimbox2.js' %}" charset="utf-8"></script>
<!-- Modernizr -->
<script type="text/javascript" src="{% static 'common/js/modernizr.custom.js' %}"></script>
<!-- Another JS -->
{% block import_js_file %}{% endblock %}
<!-- End JS -->
{% analytical_body_bottom %}
</body>
</html>
<!-- === END FOOTER === -->